# Generated by Django 5.1.7 on 2025-04-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=8, unique=True)),
                ('points_fidelite', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('camion', 'Camion'), ('camionnette', 'Camionnette'), ('utilitaire', 'Utilitaire')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_car.service')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_car.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_car.service')),
                ('tarification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_car.tarification')),
            ],
        ),
    ]
