# Generated by Django 5.1.7 on 2025-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_vehicule',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('camion', 'Camion'), ('camionnette', 'Camionnette'), ('utilitaire', 'Utilitaire')], default='inconnu', max_length=50),
        ),
    ]
