# Generated by Django 5.1.7 on 2025-03-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0002_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
