# Generated by Django 5.1.7 on 2025-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0002_rendezvous_type_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(default='en_attente', max_length=50),
        ),
    ]
