# Generated by Django 5.1.7 on 2025-04-29 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='laveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous_laveur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('assigné', 'Assigné à un laveur'), ('terminé', 'Terminé')], default='en attente', max_length=20),
        ),
    ]
