# Generated by Django 5.1.7 on 2025-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0004_customuser_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
