# Generated by Django 5.1.7 on 2025-04-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0006_client_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
    ]
